services:
  db:
    image: postgres:15
    container_name: saas-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saas_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_saas_db:/var/lib/postgresql/data

volumes:
  postgres_saas_db:

    #DATABASE_URL=postgresql://postgres:postgres@localhost:5432/saas_db
