@baseUrl = http://localhost:3000

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZTllOWQzMS1kZmUzLTRiOGYtOGZhNy01ZWI4ZTFlNDA0ZjQiLCJlbWFpbCI6ImFkbWluQHNhYXMuY29tIiwiaWF0IjoxNzc2MjEyMTQ1LCJleHAiOjE3NzYyOTg1NDV9.rHM9k1OytxAJG8_GLZ6-nunwJwZq6Zvy8T2Jp_8FCTQ
{
  "email": "test@email.com",
  "password": "123456"
}

### Sign In
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "email": "admin@saas.com",
  "password": "password123"
}

### Profile
GET {{baseUrl}}/auth/profile
Authorization: Bearer {{token}}
x-tenant-id: b30bd119-44ee-4fec-b5de-946073787919

### User Tenants
GET {{baseUrl}}/me/tenants
Authorization: Bearer {{token}}

### List Users in Tenant
GET {{baseUrl}}/users
Authorization: Bearer {{token}}
x-tenant-id: be4418bf-8f7d-4aab-a0b2-55371b8afe5c