@baseUrl = http://localhost:3000

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YTJmOWFhZi0xNTEyLTQ5ZjgtYTJjNi02OWMwZmYxZjM2ZGMiLCJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwiaWF0IjoxNzc2MjAzNDA4LCJleHAiOjE3NzYyODk4MDh9.3s8AxLYfZeZjdt0b6X0jVsP2TTodypQw2nCeNNIuTkY

### Sign Up
POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "123456"
}

### Sign In
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "123456"
}

### Profile
GET {{baseUrl}}/auth/profile
Authorization: Bearer {{token}}

### User Tenants
GET {{baseUrl}}/me/tenants
Authorization: Bearer {{token}}